/**
 * UI layer exports
 * @module balatro/ui
 */

export type {
	Position,
	Rect,
	Layout,
	LayoutConfig,
	ButtonLayout,
} from './layout';

export {
	DEFAULT_LAYOUT_CONFIG,
	calculateLayout,
	getHandCardPositions,
	getPlayedCardPositions,
	getPlayAreaCenter,
	getScoreDisplayPosition,
	getButtonLayout,
	isScreenLargeEnough,
	getMinSizeMessage,
	isPositionInRect,
	getCardIndexAtPosition,
} from './layout';

export type {
	PreviewState,
	HandPreview,
	PreviewRenderData,
	PreviewBox,
	CardHighlight,
} from './hand-preview';

export {
	PREVIEW_COLORS,
	createHandPreview,
	isScoring,
	isValidHand,
	getPreviewScore,
	getPreviewRenderData,
	getPreviewStatusLine,
	createPreviewBox,
	getCardHighlight,
	getHighlightBrightness,
} from './hand-preview';

export type {
	MenuScreen,
	MenuOption,
	OptionsMenuItem,
	MenuState,
	TitleScreenLayout,
	MenuItem,
	MenuAction,
	TitleRenderData,
	OptionsRenderData,
	MenuInput,
} from './menu';

export {
	TITLE_ART,
	TITLE_WIDTH,
	SUBTITLE,
	FOOTER_TEXT,
	createMenuState,
	getMenuItems,
	getMenuItemCount,
	navigateUp,
	navigateDown,
	getSelectedItem,
	selectMenuItem,
	handleBack,
	calculateTitleLayout,
	centerX,
	titleCenterX,
	getTitleRenderData,
	getOptionsRenderData,
	processMenuInput,
	keyToMenuInput,
	isOnTitleScreen,
	isOnOptionsScreen,
	shouldStartGame,
} from './menu';

export type {
	EndScreenType,
	EndScreenOption,
	RunStatistics,
	EndScreenState,
	EndScreenRenderData,
	EndScreenInput,
	EndScreenAction,
} from './end-screen';

export {
	VICTORY_COLOR,
	GAME_OVER_COLOR,
	createEndScreenState,
	getEndScreenOptions,
	getOptionCount,
	navigateLeft,
	navigateRight,
	getSelectedOption,
	createRunStatistics,
	createEmptyStatistics,
	formatNumber,
	formatHandType,
	getVictoryRenderData,
	getGameOverRenderData,
	getEndScreenRenderData,
	processEndScreenInput,
	keyToEndScreenInput,
	isVictoryScreen,
	isGameOverScreen,
} from './end-screen';

export type {
	HelpContext,
	HelpOverlayState,
	KeyBinding,
	KeyBindingSection,
	HelpRenderData,
	PokerHandInfo,
	BoxLine,
} from './help-overlay';

export {
	createHelpOverlayState,
	showHelpOverlay,
	hideHelpOverlay,
	toggleHelpOverlay,
	showPokerHandReference,
	togglePokerHandReference,
	getKeyBindings,
	getAllBindings,
	getPokerHandInfo,
	formatPokerHand,
	calculateBoxDimensions,
	getHelpRenderData,
	getPokerHandsRenderData,
	createBoxLines,
	createSeparatorLine,
	isHelpKey,
	isPokerHandsKey,
	isDismissKey,
	isHelpVisible,
	isShowingPokerHands,
	getOverlayTitle,
} from './help-overlay';

export type {
	ShopSection,
	PackType,
	BoosterPack,
	VoucherType,
	Voucher,
	ShopJokerSlot,
	ShopPackSlot,
	ShopVoucherSlot,
	ShopState,
	ShopAction,
	ShopInput,
	ShopRenderData,
} from './shop';

export {
	SHOP_JOKER_SLOTS,
	SHOP_PACK_SLOTS,
	BASE_REROLL_COST,
	REROLL_COST_INCREMENT,
	calculateJokerPrice,
	getRandomPack,
	getRandomVoucher,
	generateShopInventory,
	createShopState,
	getRerollCost,
	canAffordSelected,
	getSelectedPrice,
	navigateUp as shopNavigateUp,
	navigateDown as shopNavigateDown,
	navigateLeft as shopNavigateLeft,
	navigateRight as shopNavigateRight,
	navigate as shopNavigate,
	buyJoker,
	buyPack,
	buyVoucher,
	rerollShop,
	processShopInput,
	keyToShopInput,
	getShopRenderData,
	hasUnsoldItems,
	getAvailableJokers,
	getAvailablePacks,
} from './shop';

export type {
	JokerTrayMode,
	JokerTrayState,
	JokerTooltip,
	JokerCardRenderData,
	JokerTrayRenderData,
	JokerTrayInput,
	JokerTrayAction,
	TooltipLines,
} from './joker-tray';

export {
	JOKER_CARD_WIDTH,
	JOKER_CARD_HEIGHT,
	JOKER_CARD_GAP,
	TOOLTIP_DELAY_MS,
	createJokerTrayState,
	updateJokers,
	addJoker as addJokerToTray,
	removeJoker as removeJokerFromTray,
	reorderJokers,
	setMaxSlots,
	navigateLeft as jokerTrayNavigateLeft,
	navigateRight as jokerTrayNavigateRight,
	setSelectedIndex as jokerTraySetSelectedIndex,
	enterSellMode,
	enterReorderMode,
	exitMode as exitJokerTrayMode,
	setHovered as setJokerHovered,
	processJokerTrayInput,
	keyToJokerTrayInput,
	calculateTrayDimensions,
	getJokerCardPosition,
	getJokerTrayRenderData,
	formatJokerEffect,
	getJokerRarityColor,
	getSellModeText,
	getTooltipContent,
	hasRoom as jokerTrayHasRoom,
	getJokerCount,
	getSelectedJoker,
	isInSellMode,
	isInReorderMode,
	getTotalSellValue,
} from './joker-tray';

export type {
	PackItemType,
	PackItem,
	PackOpeningPhase,
	PackOpeningState,
	PackOpeningInput,
	PackOpeningAction,
	PackOpeningRenderData,
} from './pack-opening';

export {
	generateStandardPackItems,
	generateArcanaPackItems,
	generateCelestialPackItems,
	generateBuffoonPackItems,
	generatePackItems,
	openPack,
	navigateLeft as packNavigateLeft,
	navigateRight as packNavigateRight,
	selectItem as packSelectItem,
	skipRemaining,
	processPackInput,
	keyToPackInput,
	getPackOpeningRenderData,
	isPackDone,
	getPicksRemaining,
	getSelectedItems,
	getItemName,
} from './pack-opening';
